### ISSUE TITLE
ImageView does not display image when using SDLoopingVideoView

### ISSUE THREAD

**Issue by mchlbowyer** [SolsmaHawk/SDLoopingVideoView#3]
When setting a view to the SDLoopingVideoView class, ImageViews no longer display. Removing the class then allows the ImageView to display again.

**Comment by SolsmaHawk** [comment]
Hi @mchlbowyer sorry for the late reply, I haven't updated this repo in awhile. I'm going to need more information than that. Is the `SDLoopingViewView` placed above the `ImageView`?
